### ISSUE TITLE
Committee modules

### ISSUE THREAD

**Issue by kdmnk** [luksan47/mars#270]
- [ ] #378 Economic Committee: warning email if users have to pay the KKT + Netreg;  expense and income management; automatic reports
- [ ] Communicational Committee: news feed; Epistola newsletter generation;
- [x] #323 roles for commitee leaders
- [ ] #322 calendar
- [ ] private file storage (?)
- [ ] #21 public file storage eg. for committee meeting reports
- [ ] #296 commitee invitations 

will add more...

**Comment by luksan47** [comment]
I think all of these should be separate issues when we start working on this. This can be left as an umbrella. We can also go back to using Project, but I think it would make more sense with more people.

**Comment by luksan47** [comment]
For private file storage, we have Google drive.

**Comment by luksan47** [comment]
Moved issues to project, closing this umbrella.
